import test from 'node:test';
import assert from 'node:assert/strict';
import {validateAssessment,validateAssessmentRequest,callAssessmentProvider,assessmentReadiness,PROVIDER_ENDPOINT,assessmentInstructions,fingerprints,sourceCatalog,referencedSchema,resolveReferences} from '../app/assessment.mjs';
import {runAssessment,hydrateAssessment,assessmentIsCurrent} from '../app/assessment-store.mjs';
const profile={master:'Example Candidate\nWork history: Five years coordinating deliveries and project milestones.\nTools: spreadsheets and reports.\nEducation: general business degree.',summary:'Transferable stakeholder communication.'};
const vacancy={role:'Coordinator',jd:'Seeking an experienced coordinator. Main duties include stakeholder reporting. Spreadsheet proficiency is required. A project management certificate is mandatory.'};
const config={key:'test-key-not-real',model:'explicit-test-model'};
function fixture(){const quotes=['experienced coordinator','stakeholder reporting','Spreadsheet proficiency','project management certificate',''];const evidence=['Five years coordinating deliveries and project milestones.','Transferable stakeholder communication.','spreadsheets and reports.','','Example Candidate'];const types=['direct','transferable','partial','absent','direct'];return {criteria:['experience','duties','tools','qualifications','presentation'].map((id,i)=>({id,requirements:[{requirement:i===4?'Readable original CV header':quotes[i],vacancyQuote:quotes[i],evidenceQuote:evidence[i],evidenceType:types[i],priority:i===3?'mandatory':'core',kind:i===3?'credential':i===4?'presentation':'general',rationale:i===3?'No project management certificate is documented.':'Quoted source supports this credit level.'}]})),confidence:'medium',realism:'Relevant transferable coordination experience; the mandatory certificate remains unverified.'};}
class MemoryDb{
 profiles=new Map();cache=new Map();usage=new Map();jobs=new Map();
 prepare(sql){const db=this;return {bind(...a){return {async first(){
  if(sql.startsWith('SELECT payload FROM profiles'))return db.profiles.has(a[0])?{payload:JSON.stringify(db.profiles.get(a[0]))}:null;
  if(sql.startsWith('SELECT id FROM jobs'))return db.jobs.get(a[0])===a[1]?{id:a[0]}:null;
  if(sql.startsWith('SELECT * FROM assessment_cache')){const row=db.cache.get(a[0]);return row?.user_id===a[1]?{...row}:null;}
  if(sql.startsWith('SELECT result FROM assessment_cache')){const row=db.cache.get(a[0]);return row?.user_id===a[1]&&row.state==='complete'?{result:row.result}:null;}
  if(sql.startsWith('INSERT INTO assessment_cache')){const row=db.cache.get(a[0]);if(row&&!(row.user_id===a[1]&&row.state==='failed'&&a[4]===1))return null;db.cache.set(a[0],{id:a[0],user_id:a[1],state:'pending',created_at:a[2],lease_until:a[3],result:null,error:null});return {id:a[0]};}
  if(sql.startsWith('INSERT INTO assessment_usage')){const prior=db.usage.get(a[0]);if(prior&&prior.calls>=20)return null;const row={user_id:a[1],day:a[2],calls:(prior?.calls??0)+1};db.usage.set(a[0],row);return row;}
  throw Error('Unsupported fake query: '+sql);
 },async run(){
  if(sql.startsWith('UPDATE assessment_cache')){const complete=sql.includes("state='complete'"),id=a[1],row=db.cache.get(id);if(!row||row.user_id!==a[2])return {meta:{changes:0}};if(sql.includes('lease_until<=')&&row.lease_until>a[3])return {meta:{changes:0}};row.state=complete?'complete':'failed';if(complete)row.result=a[0];else row.error=a[0];return {meta:{changes:1}};}
  throw Error('Unsupported fake mutation: '+sql);
 }}}};}
}
const dbWithProfile=()=>{const db=new MemoryDb();db.profiles.set('owner',profile);return db;};
const provider=async()=>validateAssessment(fixture(),profile,vacancy);
test('server calculates five criteria, overall and career fit; mandatory evidence remains unverified',()=>{const raw=fixture();raw.overall=100;const result=validateAssessment(raw,profile,vacancy);assert.deepEqual(result.scores,[100,75,50,0,100]);assert.equal(result.overall,64);assert.equal(result.career,60);assert.equal(result.mandatory[0].status,'unverified');assert.ok(result.provisional);});
test('priority weights change criterion arithmetic and missing criteria fail',()=>{const raw=fixture();raw.criteria[0].requirements.push({...raw.criteria[0].requirements[0],priority:'mandatory',evidenceType:'absent',evidenceQuote:''});const result=validateAssessment(raw,profile,vacancy);assert.equal(result.scores[0],40);assert.throws(()=>validateAssessment({...raw,criteria:raw.criteria.slice(0,4)},profile,vacancy),/five/);});
test('fabricated CV evidence, vacancy requirements and transferable credentials are rejected',()=>{const raw=fixture();raw.criteria[0].requirements[0].evidenceQuote='Ten years as a director';assert.throws(()=>validateAssessment(raw,profile,vacancy),/evidence quote/);const requirement=fixture();requirement.criteria[1].requirements[0].vacancyQuote='Must have invented enterprise experience';assert.throws(()=>validateAssessment(requirement,profile,vacancy),/requirement quote/);const credential=fixture();Object.assign(credential.criteria[3].requirements[0],{evidenceType:'transferable',evidenceQuote:'general business degree'});assert.throws(()=>validateAssessment(credential,profile,vacancy),/cannot be met/);});
test('presentation must quote the original master, not career summary or vacancy',()=>{const raw=fixture();raw.criteria[4].requirements[0].evidenceQuote=profile.summary;assert.throws(()=>validateAssessment(raw,profile,vacancy),/master CV/);});
test('provider is fixed, structured, bounded, store:false and treats sources as data',async()=>{let called=false;await callAssessmentProvider({...config,endpoint:'https://attacker.invalid'},profile,vacancy,async(url,options)=>{called=true;assert.equal(url,PROVIDER_ENDPOINT);assert.equal(options.redirect,'manual');const data=JSON.parse(options.body);assert.equal(data.model,config.model);assert.equal(data.store,false);assert.equal(data.text.format.type,'json_schema');assert.equal(data.text.format.strict,true);assert.ok(data.max_output_tokens<=10000);const sources=JSON.parse(data.input[1].content);assert.equal(sources.vacancyRole,vacancy.role);assert.deepEqual(sources.sourceExcerpts,sourceCatalog(profile,vacancy));assert.equal(sources.originalMasterCV,undefined);assert.equal(sources.vacancy,undefined);assert.ok(assessmentInstructions.includes('untrusted data'));assert.ok(assessmentInstructions.includes('Never rewrite'));return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(referenceFixture(profile,vacancy))}]}]});});assert.ok(called);});
test('missing engine, missing master and short vacancy never invoke provider',async()=>{assert.equal(assessmentReadiness({},profile,vacancy).status,'setup_required');const db=dbWithProfile();let calls=0;const never=async()=>{calls++;throw Error('Must not run');};assert.equal((await runAssessment(db,'owner',{},profile,vacancy,false,never)).status,'setup_required');db.profiles.set('owner',{master:'',summary:''});assert.equal((await runAssessment(db,'owner',config,profile,vacancy,false,never)).status,'missing_cv');db.profiles.set('owner',profile);assert.equal((await runAssessment(db,'owner',config,profile,{...vacancy,jd:'short'},false,never)).status,'missing_vacancy');assert.equal(calls,0);});
test('client cannot substitute a master/profile, provider endpoint, or unbounded job reference',()=>{assert.equal(validateAssessmentRequest(vacancy).force,false);for(const payload of [{...vacancy,master:profile.master},{...vacancy,profile},{...vacancy,endpoint:'https://other.invalid'},{...vacancy,jobId:'x'.repeat(101)},{...vacancy,force:'yes'},null])assert.throws(()=>validateAssessmentRequest(payload));});
test('verified result is cached; changing saved CV or vacancy makes a new fingerprint',async()=>{const db=dbWithProfile();let calls=0;const p=async()=>{calls++;return provider();};const a=await runAssessment(db,'owner',config,profile,vacancy,false,p);const b=await runAssessment(db,'owner',config,profile,vacancy,false,p);assert.equal(a.status,'complete');assert.ok(b.cached);assert.equal(calls,1);assert.equal(await assessmentIsCurrent(a.assessment,profile,vacancy,config.model),true);const updated={...profile,summary:profile.summary+' Additional confirmed fact.'};db.profiles.set('owner',updated);const c=await runAssessment(db,'owner',config,profile,vacancy,false,p);assert.notEqual(a.assessment.cacheId,c.assessment.cacheId);assert.equal(await assessmentIsCurrent(a.assessment,updated,vacancy,config.model),false);const changed=await fingerprints(profile,{...vacancy,jd:vacancy.jd+' New requirement.'},config.model);assert.notEqual(a.assessment.jdHash,changed.jdHash);});
test('atomic claim prevents duplicate in-flight calls',async()=>{const db=dbWithProfile();let release,calls=0;const delayed=()=>{calls++;return new Promise(resolve=>{release=()=>resolve(validateAssessment(fixture(),profile,vacancy));});};const first=runAssessment(db,'owner',config,profile,vacancy,false,delayed);while(!release)await new Promise(resolve=>setImmediate(resolve));const second=await runAssessment(db,'owner',config,profile,vacancy,false,delayed);assert.equal(second.status,'in_progress');assert.equal(calls,1);release();assert.equal((await first).status,'complete');});
test('provider errors are cached and never retried automatically; explicit refresh may retry',async()=>{const db=dbWithProfile();let calls=0;const failing=async()=>{calls++;throw Error('Quota unavailable');};assert.equal((await runAssessment(db,'owner',config,profile,vacancy,false,failing)).status,'error');assert.equal((await runAssessment(db,'owner',config,profile,vacancy,false,failing)).status,'error');assert.equal(calls,1);await runAssessment(db,'owner',config,profile,vacancy,true,failing);assert.equal(calls,2);});
test('daily rate limit blocks the twenty-first provider call',async()=>{const db=dbWithProfile();let calls=0;const p=async()=>{calls++;return provider();};for(let i=0;i<21;i++){const result=await runAssessment(db,'owner',config,profile,{...vacancy,role:'Coordinator '+i},false,p);if(i===20)assert.equal(result.status,'daily_limit');}assert.equal(calls,20);});
test('owned jobs and cache references cannot be used by another user',async()=>{const db=dbWithProfile();db.jobs.set('private-job','owner');assert.equal((await runAssessment(db,'other',config,profile,{...vacancy,jobId:'private-job'},false,provider)).status,'not_found');const result=await runAssessment(db,'owner',config,profile,vacancy,false,provider);await assert.rejects(hydrateAssessment({...vacancy},result.assessment,db,'other',profile,config.model),/this user/);const hydrated=await hydrateAssessment({...vacancy,assessmentMode:'automatic'},result.assessment,db,'owner',profile,config.model);assert.equal(hydrated.scores[0],100);const stale=await hydrateAssessment({...vacancy,jd:vacancy.jd+' Updated.',assessmentMode:'automatic'},result.assessment,db,'owner',profile,config.model);assert.equal(stale.assessment.status,'stale');assert.equal(stale.scores,undefined);});
test('quota and timeout errors are honest and do not expose provider response data',async()=>{await assert.rejects(callAssessmentProvider(config,profile,vacancy,async()=>new Response('sensitive provider detail',{status:429})),/quota/);const stalled=(_,options)=>new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(Error('abort')),{once:true}));await assert.rejects(callAssessmentProvider(config,profile,vacancy,stalled,20),/timed out/);});

test('edge-compatible manual redirects are rejected without another request',async()=>{let calls=0;await assert.rejects(callAssessmentProvider(config,profile,vacancy,async(url,options)=>{calls++;assert.equal(url,PROVIDER_ENDPOINT);assert.equal(options.redirect,'manual');return new Response(null,{status:302,headers:{Location:'https://attacker.invalid'}});}),/redirect refused/);assert.equal(calls,1);});

function referenceFixture(p,v){const catalog=sourceCatalog(p,v),raw=fixture();for(const c of raw.criteria)for(const item of c.requirements)for(const field of ['vacancyQuote','evidenceQuote']){if(!item[field])continue;const prefix=field==='vacancyQuote'?'J':c.id==='presentation'?'M':null;item[field]=Object.keys(catalog).find(id=>(!prefix||id.startsWith(prefix))&&catalog[id].includes(item[field]));}return raw;}
test('provider source IDs resolve into verbatim evidence, never generated quotations',()=>{const catalog=sourceCatalog(profile,vacancy),raw=referenceFixture(profile,vacancy);const resolved=resolveReferences(raw,catalog);assert.ok(profile.master.includes(resolved.criteria[0].requirements[0].evidenceQuote));assert.ok(vacancy.jd.includes(resolved.criteria[0].requirements[0].vacancyQuote));assert.doesNotThrow(()=>validateAssessment(resolved,profile,vacancy));raw.criteria[0].requirements[0].evidenceQuote='Invented career claim';assert.throws(()=>resolveReferences(raw,catalog),/invalid source/);});
test('presentation schema permits only original-master IDs and evidence schema excludes vacancy IDs',()=>{const catalog=sourceCatalog(profile,vacancy),schema=referencedSchema(catalog),[career,presentation]=schema.properties.criteria.items.anyOf;assert.ok(presentation.properties.requirements.items.anyOf[0].properties.evidenceQuote.enum.every(id=>id.startsWith('M')));assert.ok(career.properties.requirements.items.anyOf[0].properties.evidenceQuote.enum.every(id=>!id.startsWith('J')));const raw=referenceFixture(profile,vacancy);raw.criteria[4].requirements[0].evidenceQuote=Object.keys(catalog).find(id=>id.startsWith('S'));assert.throws(()=>resolveReferences(raw,catalog),/invalid source/);});

test('English master evidence is accepted and changes invalidate the cached CV fingerprint',async()=>{const bilingual={...profile,masterEnglish:'English master: Coordinating property maintenance and service providers.'},catalog=sourceCatalog(bilingual,vacancy),raw=referenceFixture(profile,vacancy);raw.criteria[0].requirements[0].evidenceQuote=Object.keys(catalog).find(id=>id.startsWith('E'));const result=validateAssessment(resolveReferences(raw,catalog),bilingual,vacancy);assert.match(result.evidence[0],/property maintenance/);assert.notEqual((await fingerprints(profile,vacancy,config.model)).cvHash,(await fingerprints(bilingual,vacancy,config.model)).cvHash);});

test('fast Luna request preserves both original masters and uses explicit low reasoning without affecting other models',async()=>{const bilingual={...profile,masterEnglish:'English master: documented project coordination and landlord communication.'};for(const model of ['gpt-6-luna','other-model'])await callAssessmentProvider({...config,model},bilingual,vacancy,async(url,options)=>{const request=JSON.parse(options.body),sources=JSON.parse(request.input[1].content);assert.ok(Object.values(sources.sourceExcerpts).includes(bilingual.masterEnglish));assert.deepEqual(request.reasoning,model==='gpt-6-luna'?{effort:'low'}:undefined);return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(referenceFixture(bilingual,vacancy))}]}]});});});
