import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {germanyDay,validateLeads,canonicalLeadUrl,runDailyLeads,readDailyLeads,registerLeadMember} from '../app/leads.mjs';
import {statuses,validateJob} from '../app/model.mjs';
function database(){const sql=new DatabaseSync(':memory:');const db={prepare(query){let values=[];return {bind(...args){values=args;return this;},async first(){return sql.prepare(query).get(...values)??null;},async all(){return {results:sql.prepare(query).all(...values)};},async run(){const result=sql.prepare(query).run(...values);return {meta:{changes:result.changes}};}};},async batch(statements){return Promise.all(statements.map(s=>s.run()));}};return db;}
const profile={master:'Managed projects and coordinated contractors. '.repeat(4)};
const lead={role:'Project Coordinator',company:'Company',location:'Berlin',arrangement:'On site',country:'Germany',url:'https://jobs.company.com/vacancy/123',why:'Contractor coordination',gap:'German level unverified',tier:'Competitive',cvQuote:'coordinated contractors.',description:'Project vacancy description '.repeat(10),postingDate:'',deadline:'',salary:''};
const response={output:[{content:[{annotations:[{type:'url_citation',url:lead.url}]}]}]};
test('Follow-up is accepted before Interview in every shared stage selector',()=>{assert.ok(statuses.indexOf('Follow-up')<statuses.indexOf('Interview'));assert.equal(validateJob({role:'Role',company:'Company',status:'Follow-up'}).status,'Follow-up');});
test('Germany calendar day handles midnight and daylight saving',()=>{assert.equal(germanyDay(new Date('2026-10-08T22:30:00Z')),'2026-10-09');assert.equal(germanyDay(new Date('2026-12-08T22:30:00Z')),'2026-12-08');});
test('leads require search citations, exact CV evidence, Germany and deduplication',()=>{assert.equal(validateLeads({leads:[lead,lead],sources:[]},response,profile).leads.length,1);for(const changes of [{url:'https://jobs.company.com/invented'},{cvQuote:'Invented career'},{country:'France'}])assert.equal(validateLeads({leads:[{...lead,...changes}],sources:[]},response,profile).leads.length,0);assert.equal(validateLeads({leads:[lead],sources:[]},response,profile,[lead.url]).leads.length,0);assert.equal(canonicalLeadUrl(lead.url+'?utm_source=site'),lead.url);});
test('daily generation and dated history are user-scoped, cached and do not create applications',async()=>{const db=database();let calls=0;const discover=async()=>{calls++;return {leads:[lead],sources:['Indeed checked']};};await registerLeadMember(db,{userId:'a',email:'a@example.com'});await registerLeadMember(db,{userId:'b',email:'b@example.com'});assert.equal((await runDailyLeads(db,'a',profile,{},discover)).count,1);assert.equal((await runDailyLeads(db,'a',profile,{},discover)).cached,true);assert.equal(calls,1);assert.equal((await readDailyLeads(db,'b')).length,0);assert.equal((await readDailyLeads(db,'a'))[0].leads[0].company,'Company');await runDailyLeads(db,'b',profile,{},discover);assert.equal(calls,2);});
test('missing CV avoids provider calls; failed searches do not automatically spend again',async()=>{const db=database();let calls=0;const discover=async()=>{calls++;throw new Error('provider unavailable');};assert.equal((await runDailyLeads(db,'missing',{}, {},discover)).state,'missing_cv');assert.equal(calls,0);assert.equal((await runDailyLeads(db,'a',profile,{},discover)).state,'failed');await runDailyLeads(db,'a',profile,{},discover);assert.equal(calls,1);assert.equal((await readDailyLeads(db,'a'))[0].leads.length,0);});
test('in-flight search claim prevents duplicate cost',async()=>{const db=database();let finish;const started=runDailyLeads(db,'a',profile,{},()=>new Promise(resolve=>finish=resolve));await new Promise(resolve=>setTimeout(resolve,20));assert.equal((await runDailyLeads(db,'a',profile,{},()=>assert.fail('duplicate'))).state,'running');finish({leads:[],sources:[]});await started;});
