import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
import {publicVacancyUrl,publicAddress,parseJobShare,parseVacancy,parsePastedVacancy,fetchVacancy,boundedText,MAX_PAGE_BYTES,jobBrief} from '../app/vacancy.mjs';
import {resolveTheme,themeInitScript} from '../app/theme.mjs';
const description='<p>Coordinate projects and provide stakeholder reporting.</p><p>Requirements: experience managing deadlines, excellent communication skills and proficiency with spreadsheets.</p><h2>About us</h2><p>Our team works together to improve customer services.</p>';
const posting={ '@type':'JobPosting',title:'Project Coordinator',hiringOrganization:{name:'Example Employer'},jobLocation:{address:{addressLocality:'Berlin',addressCountry:'DE'}},description,qualifications:'Experience managing deadlines.'};
const page=`<html><script type="application/ld+json">${JSON.stringify({'@graph':[{'@type':'Organization',name:'Other'},posting]})}</script></html>`;
function mockFetcher(handler,address='93.184.216.34'){return async(url,options)=>{if(String(url).startsWith('https://cloudflare-dns.com/'))return Response.json({Status:0,Answer:[{type:1,data:address}]});return handler(String(url),options);};}
test('extract graph JobPosting, exact employer, location, meaningful description and requirements',()=>{const v=parseVacancy(page);assert.equal(v.company,'Example Employer');assert.equal(v.role,'Project Coordinator');assert.equal(v.location,'Berlin, DE');assert.match(v.description,/stakeholder reporting/);assert.match(v.requirements,/Experience managing deadlines/);assert.match(v.requirements,/spreadsheets/);assert.ok(!v.requirements.includes('Our team'));assert.equal(v.method,'Structured JobPosting data');});
test('JSON arrays and schema type URLs are supported without inferring unknown facts',()=>{const v=parseVacancy(JSON.stringify([{'@type':'https://schema.org/JobPosting',description}]),'json');assert.equal(v.company,'');assert.equal(v.role,'');assert.equal(v.location,'');assert.match(v.description,/Requirements/);});
test('HTML fallback is inert and does not use host or unrelated site name as employer',()=>{const v=parseVacancy(`<meta property="og:site_name" content="Job Board"><main><h1>Coordinator</h1>${description}<script>globalThis.compromised=true</script><style>hide</style><nav>Navigation links</nav></main>`);assert.equal(v.company,'');assert.equal(v.role,'Coordinator');assert.ok(!v.description.includes('compromised'));assert.ok(!v.description.includes('Navigation links'));assert.match(v.warning,/Verify/);});
test('malformed JSON-LD falls back to honest HTML rather than executing code',()=>{const v=parseVacancy(`<script type="application/ld+json">{broken</script><main><h1>Analyst</h1>${description}</main>`);assert.equal(v.method,'HTML page text');assert.equal(v.company,'');});
test('login pages require pasted vacancy fallback',()=>{assert.throws(()=>parseVacancy('<main><h1>Sign in</h1><p>Sign in to continue and access your account.</p></main>'),/Paste/);});
test('unrelated page headings are not promoted to job titles',()=>{assert.throws(()=>parseVacancy('<main><h1>Welcome to our company</h1><p>We provide innovative services and help customers across the world. Explore our history, team, product range and latest company announcements.</p></main>'),/Paste/);});
test('pasted extraction uses labelled facts only and keeps description',()=>{const v=parsePastedVacancy('Role: Analyst\nCompany: Example\nLocation: Hamburg\nRequirements: Excel experience.');assert.equal(v.role,'Analyst');assert.equal(v.company,'Example');assert.equal(v.location,'Hamburg');assert.match(v.requirements,/Excel/);const unlabelled=parsePastedVacancy('An exciting opportunity with an innovative team.');assert.equal(unlabelled.company,'');assert.equal(unlabelled.role,'');});
test('raw German job-board header autofills exact role, employer and postal city while preserving full text',()=>{
 const raw='Property & Asset Manager (Eigenbestand) (m/w/d)\nExample Property GmbH\nStellenbeschreibung\n45.000 € – 55.000 € pro Jahr\nTeilzeit möglich, Teilzeit, Vollzeit\nMusterstraße 101, 01234 Dresden\nVollständige Stellenbeschreibung\nProperty & Asset Manager / Immobilienverwalter (m/w/d)\nDeine Aufgaben\nBetreuung des Portfolios und der Mietverträge.\nDein Profil\nSicherer Umgang mit Word, Excel, PowerPoint und Teams\nAnalytisches Denken und lösungsorientiertes Arbeiten\nWas wir bieten\nWeiterbildung\nÜber uns\nEin Immobilienunternehmen.\nBewerbung\ncontact@example.com\nExample Investors GmbH\nMusterstraße 101, 01234 Dresden\nWie viele Jahre Erfahrung? <1 / 1–3 / >5';
 const result=parsePastedVacancy(raw);assert.equal(result.role,'Property & Asset Manager (Eigenbestand) (m/w/d)');assert.equal(result.company,'Example Property GmbH');assert.equal(result.location,'Dresden');assert.equal(result.description,raw);assert.match(result.warning,/differs/);assert.ok(result.requirements.includes('Teams'));assert.ok(result.requirements.includes('Analytisches'));assert.ok(!result.requirements.includes('Weiterbildung'));
});
test('raw English role and brand require a stable job-header context; explicit labels win',()=>{
 const raw='Senior Software Engineer\nExample Labs\nFull job description\n10001 New York\nRequirements\nStrong communication and testing skills.\nBenefits\nFlexible hours.';
 const result=parsePastedVacancy(raw);assert.equal(result.role,'Senior Software Engineer');assert.equal(result.company,'Example Labs');assert.equal(result.location,'New York');
 const labelled=parsePastedVacancy(raw+'\nRole: Backend Developer\nEmployer: Confirmed Employer LLC\nLocation: London');assert.equal(labelled.role,'Backend Developer');assert.equal(labelled.company,'Confirmed Employer LLC');assert.equal(labelled.location,'London');
});
test('general prose, job-board branding, salary and employment metadata cannot become identity',()=>{
 for(const raw of ['We are looking for a project manager.\nOur team supports customers.','Job description\nIndeed\nFull-time\n50000 € per year\nJoin our exciting team.','Our engineers help people.\ncontact@company.com','Property Manager\nIndeed\nStellenbeschreibung\nVollzeit']){const result=parsePastedVacancy(raw);assert.equal(result.company,'');if(!raw.startsWith('Property Manager'))assert.equal(result.role,'');}
});
test('ordinary comparison signs are exact while actual pasted HTML is read inertly',()=>{
 const text='Role: Analyst\nHow much experience? <1 / 1–3 / >5\nSalary >50000; team size <10.';assert.equal(parsePastedVacancy(text).description,text);
 const html=parsePastedVacancy('<h1>Project Manager</h1><p>Example Ltd</p><p>Job description</p><script>window.bad=true</script><h2>Requirements</h2><p>Testing experience.</p>');assert.ok(!html.description.includes('window.bad'));assert.equal(html.role,'Project Manager');assert.equal(html.company,'Example Ltd');
});
test('description paste UI automatically schedules extraction and protects manual edits without saving',()=>{
 const source=readFileSync(new URL('../app/desk.tsx',import.meta.url),'utf8');assert.ok(source.includes('onPaste={pasteDescription}'));assert.ok(source.includes('extractPasted(true)'));assert.ok(source.includes('latest.jd===description'));assert.ok(source.includes('session===dialogSession.current'));assert.ok(source.includes('automatic&&current.jd!==snapshot.jd'));assert.ok(source.includes('!automatic||!current[key].trim()'));
 const handler=source.slice(source.indexOf(' function pasteDescription('),source.indexOf(' function focusDescription('));assert.ok(!handler.includes('/api/jobs'));assert.ok(!handler.includes('save()'));assert.ok(handler.includes("event.clipboardData.getData('text')"));
});
test('German HTML profile section includes every bullet and explicit location without guessing employer',()=>{
 const v=parseVacancy('<meta property="og:site_name" content="Recruiting Portal"><main><h1>PMO / Projektassistenz</h1><p>Standort: Dresden</p><h2>Ihre Aufgaben</h2><p>Unterstützung bei Planung, Reporting und Terminabstimmung mit allen Projektteams.</p><h2>Ihr Profil</h2><ul><li>Abgeschlossenes wirtschaftliches Studium</li><li>Sicherer Umgang mit Microsoft Office (Word, Excel, PowerPoint, Teams)</li><li>Analytisches Denken und lösungsorientiertes Arbeiten</li><li>Sehr gute Kommunikationsfähigkeit und strukturierte Arbeitsweise</li></ul><h2>Wir bieten</h2><p>Flexible Arbeitszeiten und vielfältige Weiterbildungsmöglichkeiten.</p><h2>Kontakt</h2><p>Kontaktieren Sie unser Recruiting-Team.</p></main>');
 assert.equal(v.location,'Dresden');assert.equal(v.company,'');for(const term of ['Studium','Word','Excel','PowerPoint','Teams','Analytisches','lösungsorientiertes','Kommunikationsfähigkeit'])assert.ok(v.requirements.includes(term),term);assert.ok(!v.requirements.includes('Flexible Arbeitszeiten'));assert.ok(!v.requirements.includes('Recruiting-Team'));
});
test('explicit English employer and requirements section merge structured evidence and stop at Benefits',()=>{
 const text='<p>Employer: Example Company</p><h2>Requirements</h2><ul><li>Strong analytical and problem-solving ability</li><li>Confident with spreadsheets and presentations</li></ul><h2>Benefits</h2><p>Private healthcare and discounts.</p>';
 const plain=parseVacancy(`<main><h1>Analyst</h1>${text}</main>`);assert.equal(plain.company,'Example Company');assert.ok(plain.requirements.includes('problem-solving'));assert.ok(!plain.requirements.includes('healthcare'));
 const structured=parseVacancy(JSON.stringify({'@type':'JobPosting',title:'Analyst',description:text,qualifications:'Degree required.'}),'json');assert.equal(structured.company,'Example Company');assert.ok(structured.requirements.includes('Degree required.'));assert.ok(structured.requirements.includes('spreadsheets'));assert.ok(!structured.requirements.includes('discounts'));
});
test('reject credential URLs, unsafe schemes, local networks and numerical encodings',()=>{for(const url of ['file:///etc/passwd','javascript:alert(1)','https://user:secret@example.com','https://localhost/x','http://10.0.0.1','http://127.1','http://2130706433','http://0x7f000001','http://0177.0.0.1','http://169.254.169.254','http://[::1]','http://[::ffff:127.0.0.1]','https://site.local','https://company.internal','https://example.com:8080'])assert.throws(()=>publicVacancyUrl(url),url);assert.equal(publicVacancyUrl('https://example.com/job#apply').href,'https://example.com/job');});
test('reject reserved DNS answers including link-local, IPv4 mapped and local IPv6',()=>{for(const ip of ['0.0.0.0','127.0.0.1','10.1.1.1','172.16.0.1','192.168.1.1','169.254.169.254','100.64.0.1','198.18.0.1','224.0.0.1','::1','fc00::1','fe80::1','::ffff:127.0.0.1','2001:db8::1','2001::1','3fff::1'])assert.equal(publicAddress(ip),false,ip);assert.equal(publicAddress('8.8.8.8'),true);assert.equal(publicAddress('2606:4700:4700::1111'),true);});
test('fetch validates every redirect before requesting next page',async()=>{const called=[];const fetcher=mockFetcher(url=>{called.push(url);return new Response(null,{status:302,headers:{Location:'http://127.0.0.1/private'}});});await assert.rejects(fetchVacancy('https://example.com/jobs',fetcher),/public website/);assert.equal(called.length,1);});
test('private DNS response is rejected before vacancy request',async()=>{let requested=false;await assert.rejects(fetchVacancy('https://example.com',mockFetcher(()=>{requested=true;return new Response(page);},'10.0.0.1')),/Private/);assert.equal(requested,false);});
test('valid HTML fetch preserves original source and final URL without saving',async()=>{const v=await fetchVacancy('https://example.com/job',mockFetcher(()=>new Response(page,{headers:{'content-type':'text/html'}})));assert.equal(v.sourceUrl,'https://example.com/job');assert.equal(v.company,'Example Employer');});
test('normal job-board request reports real HTTP failure without a categorical deny',async()=>{const requested=[];await assert.rejects(fetchVacancy('https://de.indeed.com/viewjob?jk=example123&from=appshareandroid',mockFetcher(url=>{requested.push(url);return new Response('Forbidden',{status:403});})),/returned 403/);assert.equal(requested.length,1);assert.ok(requested[0].includes('jk=example123'));await assert.rejects(fetchVacancy('https://www.linkedin.com/jobs/view/123',mockFetcher(()=>new Response('Sign in',{status:401}))),/returned 401/);});
test('accessible job-board pages still extract and page/body limits remain enforced',async()=>{const extracted=await fetchVacancy('https://de.indeed.com/viewjob?jk=example123',mockFetcher(()=>new Response(page,{headers:{'content-type':'text/html'}})));assert.equal(extracted.company,'Example Employer');await assert.rejects(fetchVacancy('https://example.com',mockFetcher(()=>new Response('binary',{headers:{'content-type':'application/pdf'}}))),/not an HTML/);await assert.rejects(boundedText(new Response('x'.repeat(MAX_PAGE_BYTES+1))),/too large/);await assert.rejects(boundedText(new Response('x',{headers:{'content-length':String(MAX_PAGE_BYTES+1)}})),/too large/);});
test('mobile title-plus-URL share text preserves job ID and explicit user title',()=>{const shared=parseJobShare('Project Coordinator (m/w/d)\nhttps://de.indeed.com/viewjob?jk=fictional456&from=appshareandroid');assert.equal(shared.title,'Project Coordinator (m/w/d)');assert.equal(shared.url,'https://de.indeed.com/viewjob?jk=fictional456&from=appshareandroid');assert.equal(parseJobShare('Analyst https://example.com/jobs/123').title,'Analyst');assert.deepEqual(parseJobShare(' https://example.com/job '),{url:'https://example.com/job',title:''});});
test('share parser rejects ambiguous URLs, credentials and private targets',()=>{for(const text of ['Role https://example.com/a https://example.com/b','https://user:secret@example.com','Title\nhttp://127.0.0.1','No URL','Title\nExtra title\nhttps://example.com'])assert.throws(()=>parseJobShare(text));});
test('server share input normalizes before the same secure bounded fetch',async()=>{const extracted=await fetchVacancy('Project Coordinator\nhttps://example.com/jobs/123',mockFetcher(()=>new Response(page,{headers:{'content-type':'text/html'}})));assert.equal(extracted.sourceUrl,'https://example.com/jobs/123');assert.equal(extracted.role,'Project Coordinator');});
test('read deadline aborts a stalled request',async()=>{const fetcher=(_,options)=>new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}));await assert.rejects(fetchVacancy('https://example.com/job',fetcher,20),/timed out/);});
test('job brief includes actual source, status, requirements and manual CV instruction',()=>{const brief=jobBrief({role:'Analyst',company:'Example',location:'Berlin',url:'https://example.com/job',status:'Saved',jd:'Requirements: experience with data.',requirements:'Data experience.'});assert.match(brief,/reference only; do not tailor until I explicitly request/);assert.match(brief,/Status: Saved/);assert.match(brief,/https:\/\/example.com\/job/);assert.match(brief,/Data experience\./);assert.match(brief,/Do not rewrite my CV/);});
test('theme chooses valid persisted value or system preference safely',()=>{assert.equal(resolveTheme('light',true),'light');assert.equal(resolveTheme('dark',false),'dark');assert.equal(resolveTheme('invalid',true),'dark');assert.equal(resolveTheme(null,false),'light');for(const [saved,systemDark,expected] of [['dark',false,'dark'],[null,true,'dark'],['invalid',false,'light']]){const document={documentElement:{dataset:{},style:{}}};vm.runInNewContext(themeInitScript,{document,localStorage:{getItem:()=>saved},matchMedia:()=>({matches:systemDark})});assert.equal(document.documentElement.dataset.theme,expected);}const document={documentElement:{dataset:{},style:{}}};vm.runInNewContext(themeInitScript,{document,localStorage:{getItem:()=>{throw Error('unavailable');}},matchMedia:()=>({matches:true})});assert.equal(document.documentElement.dataset.theme,'dark');});
test('dark form and primary button palettes meet text contrast and surfaces are covered',()=>{
 const css=readFileSync(new URL('../app/globals.css',import.meta.url),'utf8');
 const luminance=hex=>{const values=hex.match(/../g).map(x=>parseInt(x,16)/255).map(x=>x<=.04045?x/12.92:((x+.055)/1.055)**2.4);return values[0]*.2126+values[1]*.7152+values[2]*.0722;};
 const ratio=(a,b)=>{const values=[luminance(a),luminance(b)].sort((x,y)=>y-x);return (values[0]+.05)/(values[1]+.05);};
 const form=css.match(/\[data-theme=dark\] input,\[data-theme=dark\] textarea,\[data-theme=dark\] select\{background:#([a-f0-9]{6});color:#([a-f0-9]{6})/);assert.ok(form);assert.ok(ratio(form[1],form[2])>=4.5);
 const primary=css.match(/\[data-theme=dark\] \.primary\{background:#([a-f0-9]{6});color:#fff/);assert.ok(primary);assert.ok(ratio(primary[1],'ffffff')>=4.5);
 for(const surface of ['.detail-modal','.error','.mobile-nav','.confirm'])assert.ok(css.includes(`[data-theme=dark] ${surface}`));
});
test('malformed huge tags are bounded and remain inert',()=>{const v=parseVacancy(`<main><h1>Coordinator</h1>${description}${'<script'.repeat(3000)}</main>`);assert.ok(v.description.length<=30000);assert.equal(v.company,'');});


