import {env} from 'cloudflare:workers';
import {defaultsForUser} from '../../profile-defaults-server';
import {savedProfile,hydrateAssessment,assessmentIsCurrent} from '../../assessment-store.mjs';
import { context, failure, json } from '../shared';
import { validateJob } from '../../model.mjs';
export async function GET(request:Request) {try {const {user,db}=await context(request);const profile=await savedProfile(db,user.userId,defaultsForUser(user));const rows=await db.prepare('SELECT id,payload,updated_at FROM jobs WHERE user_id=? ORDER BY updated_at DESC').bind(user.userId).all();return json({jobs:await Promise.all(rows.results.map(async(r:any)=>{const job={...JSON.parse(r.payload),id:r.id,updatedAt:r.updated_at};if(job.assessment&&job.assessmentMode!=='manual')job.assessment={...job.assessment,status:await assessmentIsCurrent(job.assessment,profile,job,env.OPENAI_ASSESSMENT_MODEL)?'complete':'stale'};return job;}))});}catch(e){return failure(e);}}
export async function POST(request:Request) {try {const {user,db}=await context(request);const input=await request.json() as Record<string,unknown>;let job=validateJob(input);delete job.emailEvents;job=await hydrateAssessment(job,job.assessment,db,user.userId,await savedProfile(db,user.userId,defaultsForUser(user)),env.OPENAI_ASSESSMENT_MODEL);const id=crypto.randomUUID();const updatedAt=Date.now();await db.prepare('INSERT INTO jobs(id,user_id,payload,updated_at) VALUES(?,?,?,?)').bind(id,user.userId,JSON.stringify(job),updatedAt).run();return json({job:{...job,id,updatedAt}});}catch(e){return failure(e);}}
export async function PUT(request:Request) {try {const {user,db}=await context(request);const input=await request.json() as Record<string,unknown>;if(typeof input.id!=='string')throw new Error('Missing application.');let job=validateJob(input);const existing:any=await db.prepare('SELECT payload FROM jobs WHERE id=? AND user_id=?').bind(input.id,user.userId).first();if(!existing)throw new Error('Application not found.');const stored=JSON.parse(existing.payload);job.emailEvents=stored.emailEvents??[];job=await hydrateAssessment(job,job.assessment,db,user.userId,await savedProfile(db,user.userId,defaultsForUser(user)),env.OPENAI_ASSESSMENT_MODEL);const updatedAt=Date.now();const r=await db.prepare('UPDATE jobs SET payload=?,updated_at=? WHERE id=? AND user_id=?').bind(JSON.stringify(job),updatedAt,input.id,user.userId).run();if(!r.meta.changes)throw new Error('Application not found.');return json({job:{...job,id:input.id,updatedAt}});}catch(e){return failure(e);}}
export async function DELETE(request:Request) {try {const {user,db}=await context(request);const {id}=await request.json() as {id:string};if(typeof id!=='string')throw new Error('Missing application.');const existing=await db.prepare('SELECT id FROM jobs WHERE id=? AND user_id=?').bind(id,user.userId).first();if(!existing)throw new Error('Application not found.');const files=await db.prepare('SELECT key FROM attachments WHERE job_id=? AND user_id=?').bind(id,user.userId).all();const {env}=await import('cloudflare:workers');if(files.results.length&&!env.BUCKET)throw new Error('Document storage is unavailable. Try again before deleting.');for(const f of files.results)await env.BUCKET!.delete(String(f.key));await db.batch([db.prepare('DELETE FROM attachments WHERE job_id=? AND user_id=?').bind(id,user.userId),db.prepare('DELETE FROM jobs WHERE id=? AND user_id=?').bind(id,user.userId)]);return json({ok:true});}catch(e){return failure(e);}}

